# Generated by Django 5.2.7 on 2025-10-17 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_owner_material_owner_test_owner_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, help_text='Укажите дату оплаты', null=True, verbose_name='Дата платежа')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Укажите сумму платежа', max_digits=10, null=True, verbose_name='Сумма платежа')),
                ('payment_type', models.CharField(blank=True, choices=[('card', 'картой'), ('to_account', 'переводом на счёт')], help_text='Выберите способ оплаты', max_length=20, null=True, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('failed', 'Не удалось')], default='pending', help_text='Текущий статус оплаты', max_length=20, verbose_name='Статус платежа')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Session ID')),
                ('stripe_payment_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус оплаты в Stripe')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания платежа')),
                ('paid_course', models.ForeignKey(blank=True, help_text='Укажите оплаченный курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.course', verbose_name='Оплаченный курс')),
                ('paid_material', models.ForeignKey(blank=True, help_text='Укажите оплаченный урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.material', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='lms.course', verbose_name='Курс')),
                ('user_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('user_sub', 'course')},
            },
        ),
    ]
