# Generated by Django 5.2.7 on 2025-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="Ученик",
                help_text="Укажите своё имя",
                max_length=100,
                verbose_name="Имя",
            ),
        ),
    ]
