# Generated by Django 5.2.7 on 2025-10-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=200, verbose_name='Курс')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите стоимость курса в рублях', max_digits=10, verbose_name='Цена курса')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите картинку курса', null=True, upload_to='lms/images', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, help_text='Расскажите о своём курсе', null=True, verbose_name='Описание курса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название материала', max_length=250, verbose_name='Материал')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите стоимость материала в рублях', max_digits=10, verbose_name='Цена материала')),
                ('content', models.TextField(help_text='Разместите текст или ссылку на файл', verbose_name='Содержание материала')),
                ('illustration', models.ImageField(blank=True, help_text='Загрузите иллюстрацию к материалу', null=True, upload_to='lms/illustrations', verbose_name='Иллюстрация')),
                ('video_link', models.TextField(blank=True, help_text='Введите ссылку на видео', null=True, verbose_name='Ссылка на видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Укажите курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lms.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='lms.material')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('score', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lms.test')),
            ],
        ),
    ]
