# Generated by Django 5.2.7 on 2025-10-14 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Введите название курса', max_length=200, verbose_name='Курс')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите стоимость курса в рублях', max_digits=10, verbose_name='Цена курса')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите картинку курса', null=True, upload_to='study/previews', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, help_text='Расскажите о своём курсе', null=True, verbose_name='Описание курса')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(help_text='Введите название урока', max_length=250, verbose_name='Урок')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите стоимость урока в рублях', max_digits=10, verbose_name='Цена урока')),
                ('lesson_description', models.TextField(help_text='Расскажите об уроке', verbose_name='Описание урока')),
                ('preview_l', models.ImageField(blank=True, help_text='Загрузите картинку урока', null=True, upload_to='study/preview_l', verbose_name='Картинка')),
                ('video_link', models.TextField(blank=True, help_text='Введите ссылку на видео', null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, help_text='Укажите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lms.course', verbose_name='Курс')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='lms.course', verbose_name='Курс')),
                ('user_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('user_sub', 'course')},
            },
        ),
    ]
