# Generated by Django 5.2.7 on 2025-11-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, help_text='Загрузите картинку курса', null=True, upload_to='courses/previews/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='material',
            name='illustration',
            field=models.ImageField(blank=True, help_text='Загрузите иллюстрацию к материалу', null=True, upload_to='materials/illustrations', verbose_name='Иллюстрация'),
        ),
    ]
