# Generated by Django 5.2.7 on 2025-11-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_testattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestResult",
        ),
    ]
